name: Lint Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install flake8 and black
        run: |
          pip install flake8 black

      - name: Run flake8
        run: |
          flake8 app.py database_operations.py tests

      - name: Check code format with black
        run: |
          black --check .
