name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -x tests,venv,.venv,__pycache__ -s B101,B311
